import "server-only";

import type { D1Like } from "@portfolio/database";
import type { ObjectStorage } from "@portfolio/types";

import { DatabaseUnavailableError } from "./db/binding.ts";
import { StorageUnavailableError } from "./storage/binding.ts";

/**
 * The production counterpart of `dev-platform.ts`.
 *
 * `dev-platform.ts` resolves bindings from Wrangler's `getPlatformProxy()`
 * for `next dev`. This module resolves them from the real Worker environment,
 * and the two never both apply: `instrumentation.ts` registers these providers
 * only in a production build, and the seams fall back to the development
 * platform only when nothing is registered.
 *
 * ## Why it takes a reader instead of importing the adapter
 *
 * The obvious shape is to call `getCloudflareContext()` here. It is not done
 * that way so this module can be tested in plain Node with no Cloudflare
 * runtime at all — the missing-binding behaviour below is the part most worth
 * testing, and it would otherwise be reachable only by deploying.
 *
 * `instrumentation.ts` supplies the real reader. That file is one line of
 * wiring and no logic, which is the right split.
 *
 * ## Build time, isolate start, request time
 *
 * These are three different moments and only the last one has bindings.
 *
 *   * **Build time** — `next build` runs on a machine with no Worker `env`.
 *     Nothing here executes: this module only *defines* functions.
 *   * **Isolate start** — `register()` runs once and stores a closure. Still
 *     no binding is touched, so an isolate can start even if the config is
 *     wrong; it fails on the first request instead, with a clear message.
 *   * **Request time** — the closure runs, reads `env`, and returns the
 *     binding. This is the only moment `getCloudflareContext()` can answer.
 *
 * Reading a binding at module scope would invert that and break the build.
 */

/**
 * The two bindings this app needs, as **structural** types.
 *
 * Deliberately `D1Like` and `ObjectStorage` — the project's own narrow
 * interfaces — rather than `D1Database` and `R2Bucket` from
 * `@cloudflare/workers-types`, which this repository does not depend on and
 * does not want to. See `docs/ARCHITECTURE.md`.
 *
 * That the real bindings satisfy these interfaces is verified rather than
 * asserted: `packages/database/scripts/d1-type-compatibility.mjs` compiles a
 * real `D1Database` against `D1Like`, and
 * `apps/admin/scripts/storage-foundation-tests.mjs` compiles a real `R2Bucket`
 * against `ObjectStorage` using types generated by `wrangler types`. Both run
 * in `pnpm test`.
 *
 * Optional, because a Worker deployed without one of the bindings is a real
 * and recoverable situation — a config mistake, not an impossibility — and the
 * type should say so instead of letting `undefined` through as a valid
 * database.
 */
export interface CloudflarePlatformBindings {
  readonly DB?: D1Like;
  readonly MEDIA?: ObjectStorage;
}

declare global {
  /**
   * Augments the adapter's `CloudflareEnv` with this app's own bindings, so
   * `getCloudflareContext().env.DB` type-checks without a cast.
   *
   * The two members are spelled out rather than inherited from
   * `CloudflarePlatformBindings`: an interface that only extends another
   * declares no members of its own, which the lint config rejects — and in an
   * ambient augmentation it would also read as though nothing were being
   * added.
   */
  interface CloudflareEnv {
    DB?: D1Like;
    MEDIA?: ObjectStorage;
  }
}

/** Reads the current Worker environment. Supplied by `instrumentation.ts`. */
export type CloudflareEnvReader = () => Promise<CloudflarePlatformBindings>;

/** The shape of `globalThis` this module needs. Injectable, so it is testable. */
export interface RuntimeGlobals {
  readonly navigator?: { readonly userAgent?: string };
}

/**
 * Whether this code is running inside the Workers runtime.
 *
 * Load-bearing, and the reason is a real trap in the adapter rather than
 * caution. `getCloudflareContext({ async: true })` does **not** simply fail
 * when there is no Worker context: if `NEXT_RUNTIME` is `nodejs` it falls back
 * to Wrangler's `getPlatformProxy()` and returns **miniflare's local bindings**
 * instead. That is a deliberate convenience for `next dev`, and it is exactly
 * the wrong answer for a production build.
 *
 * Without this check, `next start` — a production build running on Node, and a
 * script this repository still defines — would pass both of
 * `instrumentation.ts`'s other guards, register these providers, and then serve
 * the public site from the local `.wrangler/state` database while looking
 * entirely healthy. Silently serving the wrong database is the single failure
 * the binding seams exist to prevent, so it cannot be reintroduced here.
 *
 * With the check, `next start` registers nothing, the seam finds no provider,
 * and it fails closed with its own message — the behaviour that was already
 * observed and expected before this slice.
 *
 * `navigator.userAgent` is workerd's own identifier. It is present whenever
 * the `global_navigator` compatibility flag is on, which is the default for
 * every compatibility date after 2022-03-21; this Worker is pinned far later.
 */
export function isWorkersRuntime(
  globals: RuntimeGlobals = globalThis,
): boolean {
  return globals.navigator?.userAgent === "Cloudflare-Workers";
}

/**
 * Resolves the D1 binding for a request.
 *
 * Fails closed in both directions: if the environment cannot be read at all,
 * or if it can be read but carries no `DB`, this throws. There is deliberately
 * no fallback to the development platform — a production Worker quietly
 * serving miniflare's local database, or an empty one, is worse than an error.
 */
export function createProductionDatabaseProvider(
  readEnv: CloudflareEnvReader,
): () => Promise<D1Like> {
  return async () => {
    let env: CloudflarePlatformBindings;
    try {
      env = await readEnv();
    } catch (cause) {
      const error = new DatabaseUnavailableError(
        "the Cloudflare runtime context was not available for this request",
      );
      error.cause = cause;
      throw error;
    }

    const database = env.DB;
    if (!database) {
      // Names the fix, because this is a deployment error and whoever reads
      // the log is looking at a config file, not at this code.
      throw new DatabaseUnavailableError(
        "the Worker has no DB binding. Add a d1_databases entry binding " +
          "`DB` to the portfolio-cms database in apps/web/wrangler.jsonc",
      );
    }

    return database;
  };
}

/**
 * Resolves the R2 binding for a request.
 *
 * The public site only reads — `/media/[id]` serves bytes — but the binding is
 * the same object either way, and the seam's contract is `ObjectStorage`.
 */
export function createProductionStorageProvider(
  readEnv: CloudflareEnvReader,
): () => Promise<ObjectStorage> {
  return async () => {
    let env: CloudflarePlatformBindings;
    try {
      env = await readEnv();
    } catch (cause) {
      const error = new StorageUnavailableError(
        "the Cloudflare runtime context was not available for this request",
      );
      error.cause = cause;
      throw error;
    }

    const bucket = env.MEDIA;
    if (!bucket) {
      throw new StorageUnavailableError(
        "the Worker has no MEDIA binding. Add an r2_buckets entry binding " +
          "`MEDIA` to the portfolio-media bucket in apps/web/wrangler.jsonc",
      );
    }

    return bucket;
  };
}
